[package]
name = "cli-calc"
version = "0.1.0"
authors = ["Srikanth Kotturi"]
edition = "2021"

[dependencies]
clap = {version = "4.5.6", features = ["derive"]}

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
